"""remove soft deletes

Revision ID: 51099eaf88b7
Revises: 0002
Create Date: 2026-05-06 17:33:12.184549

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'deleted_at')
    op.drop_column('groups', 'deleted_at')
    op.drop_column('mcp_servers', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.add_column('groups', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.add_column('api_keys', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
